### ISSUE TITLE
btxe output can't be read by Playground engine

### ISSUE THREAD

**Issue by MikuAuahDark** [summertriangle-dev/hatedelay#3]
Using `btxe test.texb test.png test2.texb` then `extb test2.texb .` gives me "cannot initialize zlib" error.

**Comment by summertriangle-dev** [comment]
I'm going to need samples

**Comment by MikuAuahDark** [comment]
Looks it I can solve it by adding `O_BINARY` when opening the file. But the output of the .texb seems can't be read by the Playground OSS engine (extb can read it without problems)

**Comment by summertriangle-dev** [comment]
I'm going to need samples

**Comment by MikuAuahDark** [comment]
Oh sorry, I didn't notice your reply. [Here you go](https://drive.google.com/file/d/0B_b5QBR6jboZck1aSkwtZHNZc3c/view?usp=sharing)

**Comment by summertriangle-dev** [comment]
Have you tried it under Mac OS/Linux?

I'm assuming it has something to do with the way windows mangles line endings.

**Comment by MikuAuahDark** [comment]
> I'm assuming it has something to do with the way windows mangles line endings.

Actually I fixed this

> Looks it I can solve it by adding `O_BINARY` when opening the file.

But I tried it under Linux and this problem still exist

> But the output of the .texb seems can't be read by the Playground OSS engine (**extb can read it without problems**)

**Comment by summertriangle-dev** [comment]
My extb can't read the sample you posted.

**Comment by MikuAuahDark** [comment]
[Try this sample](https://drive.google.com/file/d/0B_b5QBR6jboZYjkxd2s1XzB0Q0E/view?usp=sharing)

My extb can read that file without problems

**Comment by summertriangle-dev** [comment]
There are 4680 bytes of garbage at the end of that file (the correct size is [the u32 right after TEXB in the file header + 8] bytes; this is enforced by playground as an assert). After removing it the file loads correctly on my iPad.

I was not able to reproduce this behaviour when replacing a bank under Mac OS X, so you're on your own.

edit: Also, curiously enough, 4680 is the number of newlines in the file. This should give you a good idea of where to start.

**Comment by MikuAuahDark** [comment]
Well, I do exactly what you said (removing the 4680 bytes at the end of the file) and it works. Now I know why it's not working. I can write a Lua script for dirty workaround solution, but if you can, please fix it as soon as possible.

**Comment by summertriangle-dev** [comment]
I can do it if you mail me a windows laptop

**Comment by MikuAuahDark** [comment]
But actually it also happend in Ubuntu.
